package com.monopolyfun.modules.order.service.view;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;

public record OrderSummary(
        String id,
        String orderNo,
        String orderName,
        String postKind,
        String postId,
        String parentOrderId,
        String status,
        String displayPhase,
        String claimedByAccountId,
        String buyerAccountId,
        String sellerAccountId,
        String fulfillerAccountId,
        String acceptorAccountId,
        String roleModelVersion,
        String currentAccountRole,
        String submittedByAccountId,
        String acceptedByAccountId,
        String reviewerAccountId,
        Instant reviewDueAt,
        String proofId,
        String settlementType,
        BigDecimal settlementAmount,
        String itemId,
        String fulfillmentMode,
        String deliveryMode,
        String deliverySource,
        String buyerNote,
        String paymentMethod,
        Object deliveryPayload,
        Object deliveryReceipt,
        String agentRuntimeId,
        Integer reservedShares,
        Instant lockExpiresAt,
        Instant lastProgressAt,
        Instant nextProgressDueAt,
        int progressCount,
        String disputeReason,
        String reviewPostId,
        String disputeOpenedByAccountId,
        String disputeOpenedFromStatus,
        String disputeOpenedFromWindowStatus,
        Instant disputeOpenedFromWindowExpiresAt,
        Instant disputeOpenedAt,
        String disputeCancelledByAccountId,
        Instant disputeCancelledAt,
        String disputeCancelReason,
        String backofficeOverrideDecision,
        String backofficeOverrideReason,
        String challengeNonce,
        boolean settlementFrozen,
        List<String> acceptanceCriteriaSnapshot,
        String proofSpecSnapshot,
        String settlementSpecSnapshot,
        String reviewStatus,
        String disputeWindowStatus,
        Instant disputeWindowExpiresAt,
        Instant finalizedAt,
        Instant createdAt,
        Instant updatedAt,
        String paymentIntentStatus,
        Instant paymentDueAt,
        @JsonInclude(JsonInclude.Include.NON_NULL)
        String resourceKey,
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        List<String> capabilities,
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        List<Map<String, Object>> blockedCapabilities
) {
    public OrderSummary(
            String id,
            String orderNo,
            String orderName,
            String postKind,
            String postId,
            String parentOrderId,
            String status,
            String displayPhase,
            String claimedByAccountId,
            String buyerAccountId,
            String sellerAccountId,
            String fulfillerAccountId,
            String acceptorAccountId,
            String roleModelVersion,
            String currentAccountRole,
            String submittedByAccountId,
            String acceptedByAccountId,
            String reviewerAccountId,
            Instant reviewDueAt,
            String proofId,
            String settlementType,
            BigDecimal settlementAmount,
            String itemId,
            String fulfillmentMode,
            String deliveryMode,
            String deliverySource,
            String buyerNote,
            String paymentMethod,
            Object deliveryPayload,
            Object deliveryReceipt,
            String agentRuntimeId,
            Integer reservedShares,
            Instant lockExpiresAt,
            Instant lastProgressAt,
            Instant nextProgressDueAt,
            int progressCount,
            String disputeReason,
            String reviewPostId,
            String disputeOpenedByAccountId,
            String disputeOpenedFromStatus,
            String disputeOpenedFromWindowStatus,
            Instant disputeOpenedFromWindowExpiresAt,
            Instant disputeOpenedAt,
            String disputeCancelledByAccountId,
            Instant disputeCancelledAt,
            String disputeCancelReason,
            String backofficeOverrideDecision,
            String backofficeOverrideReason,
            String challengeNonce,
            boolean settlementFrozen,
            List<String> acceptanceCriteriaSnapshot,
            String proofSpecSnapshot,
            String settlementSpecSnapshot,
            String reviewStatus,
            String disputeWindowStatus,
            Instant disputeWindowExpiresAt,
            Instant finalizedAt,
            Instant createdAt,
            Instant updatedAt) {
        this(
                id,
                orderNo,
                orderName,
                postKind,
                postId,
                parentOrderId,
                status,
                displayPhase,
                claimedByAccountId,
                buyerAccountId,
                sellerAccountId,
                fulfillerAccountId,
                acceptorAccountId,
                roleModelVersion,
                currentAccountRole,
                submittedByAccountId,
                acceptedByAccountId,
                reviewerAccountId,
                reviewDueAt,
                proofId,
                settlementType,
                settlementAmount,
                itemId,
                fulfillmentMode,
                deliveryMode,
                deliverySource,
                buyerNote,
                paymentMethod,
                deliveryPayload,
                deliveryReceipt,
                agentRuntimeId,
                reservedShares,
                lockExpiresAt,
                lastProgressAt,
                nextProgressDueAt,
                progressCount,
                disputeReason,
                reviewPostId,
                disputeOpenedByAccountId,
                disputeOpenedFromStatus,
                disputeOpenedFromWindowStatus,
                disputeOpenedFromWindowExpiresAt,
                disputeOpenedAt,
                disputeCancelledByAccountId,
                disputeCancelledAt,
                disputeCancelReason,
                backofficeOverrideDecision,
                backofficeOverrideReason,
                challengeNonce,
                settlementFrozen,
                acceptanceCriteriaSnapshot,
                proofSpecSnapshot,
                settlementSpecSnapshot,
                reviewStatus,
                disputeWindowStatus,
                disputeWindowExpiresAt,
                finalizedAt,
                createdAt,
                updatedAt,
                null,
                null,
                null,
                List.of(),
                List.of());
    }

    public OrderSummary {
        acceptanceCriteriaSnapshot = acceptanceCriteriaSnapshot == null ? List.of() : List.copyOf(acceptanceCriteriaSnapshot);
        capabilities = capabilities == null ? List.of() : List.copyOf(capabilities);
        blockedCapabilities = blockedCapabilities == null ? List.of() : List.copyOf(blockedCapabilities);
    }

    public OrderSummary withAgentState(
            String resourceKey,
            List<String> capabilities,
            List<Map<String, Object>> blockedCapabilities) {
        return new OrderSummary(
                id,
                orderNo,
                orderName,
                postKind,
                postId,
                parentOrderId,
                status,
                displayPhase,
                claimedByAccountId,
                buyerAccountId,
                sellerAccountId,
                fulfillerAccountId,
                acceptorAccountId,
                roleModelVersion,
                currentAccountRole,
                submittedByAccountId,
                acceptedByAccountId,
                reviewerAccountId,
                reviewDueAt,
                proofId,
                settlementType,
                settlementAmount,
                itemId,
                fulfillmentMode,
                deliveryMode,
                deliverySource,
                buyerNote,
                paymentMethod,
                deliveryPayload,
                deliveryReceipt,
                agentRuntimeId,
                reservedShares,
                lockExpiresAt,
                lastProgressAt,
                nextProgressDueAt,
                progressCount,
                disputeReason,
                reviewPostId,
                disputeOpenedByAccountId,
                disputeOpenedFromStatus,
                disputeOpenedFromWindowStatus,
                disputeOpenedFromWindowExpiresAt,
                disputeOpenedAt,
                disputeCancelledByAccountId,
                disputeCancelledAt,
                disputeCancelReason,
                backofficeOverrideDecision,
                backofficeOverrideReason,
                challengeNonce,
                settlementFrozen,
                acceptanceCriteriaSnapshot,
                proofSpecSnapshot,
                settlementSpecSnapshot,
                reviewStatus,
                disputeWindowStatus,
                disputeWindowExpiresAt,
                finalizedAt,
                createdAt,
                updatedAt,
                paymentIntentStatus,
                paymentDueAt,
                resourceKey,
                capabilities,
                blockedCapabilities);
    }

    public OrderSummary withPaymentState(String paymentIntentStatus, Instant paymentDueAt) {
        return new OrderSummary(
                id,
                orderNo,
                orderName,
                postKind,
                postId,
                parentOrderId,
                status,
                displayPhase,
                claimedByAccountId,
                buyerAccountId,
                sellerAccountId,
                fulfillerAccountId,
                acceptorAccountId,
                roleModelVersion,
                currentAccountRole,
                submittedByAccountId,
                acceptedByAccountId,
                reviewerAccountId,
                reviewDueAt,
                proofId,
                settlementType,
                settlementAmount,
                itemId,
                fulfillmentMode,
                deliveryMode,
                deliverySource,
                buyerNote,
                paymentMethod,
                deliveryPayload,
                deliveryReceipt,
                agentRuntimeId,
                reservedShares,
                lockExpiresAt,
                lastProgressAt,
                nextProgressDueAt,
                progressCount,
                disputeReason,
                reviewPostId,
                disputeOpenedByAccountId,
                disputeOpenedFromStatus,
                disputeOpenedFromWindowStatus,
                disputeOpenedFromWindowExpiresAt,
                disputeOpenedAt,
                disputeCancelledByAccountId,
                disputeCancelledAt,
                disputeCancelReason,
                backofficeOverrideDecision,
                backofficeOverrideReason,
                challengeNonce,
                settlementFrozen,
                acceptanceCriteriaSnapshot,
                proofSpecSnapshot,
                settlementSpecSnapshot,
                reviewStatus,
                disputeWindowStatus,
                disputeWindowExpiresAt,
                finalizedAt,
                createdAt,
                updatedAt,
                paymentIntentStatus,
                paymentDueAt,
                resourceKey,
                capabilities,
                blockedCapabilities);
    }
}
