package com.monopolyfun.modules.post.service.view;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;

public record PostItemView(
        String id,
        String postKind,
        String postId,
        String marketId,
        String title,
        String summary,
        String deliverableSpec,
        String acceptanceSpec,
        List<String> acceptanceCriteria,
        String itemKind,
        String fulfillmentMode,
        String deliveryMode,
        String deliverySource,
        String deliveryProvider,
        String deliverySlaLabel,
        String deliveryFailurePolicy,
        String buyerNotePlaceholder,
        String agentInstruction,
        String priority,
        String settlementType,
        BigDecimal priceAmount,
        BigDecimal budgetAmount,
        String currency,
        String paymentMethod,
        String paymentNetwork,
        String paymentRecipient,
        Double difficultyScore,
        Integer rewardPreviewShares,
        Integer reservedShares,
        int seatCount,
        int activeOrdersCount,
        String status,
        String claimedByAccountId,
        String activeOrderNo,
        String activeOrderDisplayPhase,
        boolean activeOrderPaymentRequired,
        String activeOrderPaymentStatus,
        Instant lockExpiresAt,
        Instant nextProgressDueAt,
        Instant updatedAt,
        @JsonInclude(JsonInclude.Include.NON_NULL)
        String resourceKey,
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        List<String> capabilities,
        @JsonInclude(JsonInclude.Include.NON_EMPTY)
        List<Map<String, Object>> blockedCapabilities
) {
    public PostItemView(
            String id,
            String postKind,
            String postId,
            String marketId,
            String title,
            String summary,
            String deliverableSpec,
            String acceptanceSpec,
            List<String> acceptanceCriteria,
            String itemKind,
            String fulfillmentMode,
            String deliveryMode,
            String deliverySource,
            String deliveryProvider,
            String deliverySlaLabel,
            String deliveryFailurePolicy,
            String buyerNotePlaceholder,
            String agentInstruction,
            String priority,
            String settlementType,
            BigDecimal priceAmount,
            BigDecimal budgetAmount,
            String currency,
            String paymentMethod,
            String paymentNetwork,
            String paymentRecipient,
            Double difficultyScore,
            Integer rewardPreviewShares,
            Integer reservedShares,
            int seatCount,
            int activeOrdersCount,
            String status,
            String claimedByAccountId,
            String activeOrderNo,
            String activeOrderDisplayPhase,
            boolean activeOrderPaymentRequired,
            String activeOrderPaymentStatus,
            Instant lockExpiresAt,
            Instant nextProgressDueAt,
            Instant updatedAt) {
        this(
                id,
                postKind,
                postId,
                marketId,
                title,
                summary,
                deliverableSpec,
                acceptanceSpec,
                acceptanceCriteria,
                itemKind,
                fulfillmentMode,
                deliveryMode,
                deliverySource,
                deliveryProvider,
                deliverySlaLabel,
                deliveryFailurePolicy,
                buyerNotePlaceholder,
                agentInstruction,
                priority,
                settlementType,
                priceAmount,
                budgetAmount,
                currency,
                paymentMethod,
                paymentNetwork,
                paymentRecipient,
                difficultyScore,
                rewardPreviewShares,
                reservedShares,
                seatCount,
                activeOrdersCount,
                status,
                claimedByAccountId,
                activeOrderNo,
                activeOrderDisplayPhase,
                activeOrderPaymentRequired,
                activeOrderPaymentStatus,
                lockExpiresAt,
                nextProgressDueAt,
                updatedAt,
                null,
                List.of(),
                List.of());
    }

    public PostItemView {
        acceptanceCriteria = acceptanceCriteria == null ? List.of() : List.copyOf(acceptanceCriteria);
        capabilities = capabilities == null ? List.of() : List.copyOf(capabilities);
        blockedCapabilities = blockedCapabilities == null ? List.of() : List.copyOf(blockedCapabilities);
    }

    public PostItemView withAgentState(
            String resourceKey,
            List<String> capabilities,
            List<Map<String, Object>> blockedCapabilities) {
        return new PostItemView(
                id,
                postKind,
                postId,
                marketId,
                title,
                summary,
                deliverableSpec,
                acceptanceSpec,
                acceptanceCriteria,
                itemKind,
                fulfillmentMode,
                deliveryMode,
                deliverySource,
                deliveryProvider,
                deliverySlaLabel,
                deliveryFailurePolicy,
                buyerNotePlaceholder,
                agentInstruction,
                priority,
                settlementType,
                priceAmount,
                budgetAmount,
                currency,
                paymentMethod,
                paymentNetwork,
                paymentRecipient,
                difficultyScore,
                rewardPreviewShares,
                reservedShares,
                seatCount,
                activeOrdersCount,
                status,
                claimedByAccountId,
                activeOrderNo,
                activeOrderDisplayPhase,
                activeOrderPaymentRequired,
                activeOrderPaymentStatus,
                lockExpiresAt,
                nextProgressDueAt,
                updatedAt,
                resourceKey,
                capabilities,
                blockedCapabilities);
    }
}
